CREATE SCHEMA IF NOT EXISTS "session" AUTHORIZATION postgres;

-- Permissions

GRANT ALL ON SCHEMA "session" TO postgres;
GRANT ALL ON SCHEMA "session" TO session_manager;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "session" GRANT ALL ON SEQUENCES TO session_manager;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "session" GRANT USAGE ON TYPES TO session_manager;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "session" GRANT EXECUTE ON FUNCTIONS TO session_manager;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "session" GRANT ALL ON TABLES TO session_manager;