// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.26.1
// source: cadets_time.proto

package session_manager

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MonthNumber int32

const (
	MonthNumber_UNSPECIFIED MonthNumber = 0
	MonthNumber_january     MonthNumber = 1
	MonthNumber_february    MonthNumber = 2
	MonthNumber_march       MonthNumber = 3
	MonthNumber_april       MonthNumber = 4
	MonthNumber_may         MonthNumber = 5
	MonthNumber_june        MonthNumber = 6
	MonthNumber_july        MonthNumber = 7
	MonthNumber_august      MonthNumber = 8
	MonthNumber_september   MonthNumber = 9
	MonthNumber_october     MonthNumber = 10
	MonthNumber_november    MonthNumber = 11
	MonthNumber_december    MonthNumber = 12
)

// Enum value maps for MonthNumber.
var (
	MonthNumber_name = map[int32]string{
		0:  "UNSPECIFIED",
		1:  "january",
		2:  "february",
		3:  "march",
		4:  "april",
		5:  "may",
		6:  "june",
		7:  "july",
		8:  "august",
		9:  "september",
		10: "october",
		11: "november",
		12: "december",
	}
	MonthNumber_value = map[string]int32{
		"UNSPECIFIED": 0,
		"january":     1,
		"february":    2,
		"march":       3,
		"april":       4,
		"may":         5,
		"june":        6,
		"july":        7,
		"august":      8,
		"september":   9,
		"october":     10,
		"november":    11,
		"december":    12,
	}
)

func (x MonthNumber) Enum() *MonthNumber {
	p := new(MonthNumber)
	*p = x
	return p
}

func (x MonthNumber) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MonthNumber) Descriptor() protoreflect.EnumDescriptor {
	return file_cadets_time_proto_enumTypes[0].Descriptor()
}

func (MonthNumber) Type() protoreflect.EnumType {
	return &file_cadets_time_proto_enumTypes[0]
}

func (x MonthNumber) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MonthNumber.Descriptor instead.
func (MonthNumber) EnumDescriptor() ([]byte, []int) {
	return file_cadets_time_proto_rawDescGZIP(), []int{0}
}

type MonthNum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Year  string      `protobuf:"bytes,1,opt,name=year,proto3" json:"year,omitempty"`
	Month MonthNumber `protobuf:"varint,2,opt,name=month,proto3,enum=session_manager.MonthNumber" json:"month,omitempty"`
	Hours float32     `protobuf:"fixed32,3,opt,name=hours,proto3" json:"hours,omitempty"`
}

func (x *MonthNum) Reset() {
	*x = MonthNum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cadets_time_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MonthNum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonthNum) ProtoMessage() {}

func (x *MonthNum) ProtoReflect() protoreflect.Message {
	mi := &file_cadets_time_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonthNum.ProtoReflect.Descriptor instead.
func (*MonthNum) Descriptor() ([]byte, []int) {
	return file_cadets_time_proto_rawDescGZIP(), []int{0}
}

func (x *MonthNum) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *MonthNum) GetMonth() MonthNumber {
	if x != nil {
		return x.Month
	}
	return MonthNumber_UNSPECIFIED
}

func (x *MonthNum) GetHours() float32 {
	if x != nil {
		return x.Hours
	}
	return 0
}

type Cadet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int32       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Total float32     `protobuf:"fixed32,2,opt,name=total,proto3" json:"total,omitempty"`
	Month []*MonthNum `protobuf:"bytes,3,rep,name=month,proto3" json:"month,omitempty"`
}

func (x *Cadet) Reset() {
	*x = Cadet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cadets_time_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cadet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cadet) ProtoMessage() {}

func (x *Cadet) ProtoReflect() protoreflect.Message {
	mi := &file_cadets_time_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cadet.ProtoReflect.Descriptor instead.
func (*Cadet) Descriptor() ([]byte, []int) {
	return file_cadets_time_proto_rawDescGZIP(), []int{1}
}

func (x *Cadet) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Cadet) GetTotal() float32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Cadet) GetMonth() []*MonthNum {
	if x != nil {
		return x.Month
	}
	return nil
}

type CadetsTimeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Cadets  []*Cadet `protobuf:"bytes,2,rep,name=cadets,proto3" json:"cadets,omitempty"`
}

func (x *CadetsTimeResponse) Reset() {
	*x = CadetsTimeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cadets_time_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CadetsTimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CadetsTimeResponse) ProtoMessage() {}

func (x *CadetsTimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cadets_time_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CadetsTimeResponse.ProtoReflect.Descriptor instead.
func (*CadetsTimeResponse) Descriptor() ([]byte, []int) {
	return file_cadets_time_proto_rawDescGZIP(), []int{2}
}

func (x *CadetsTimeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CadetsTimeResponse) GetCadets() []*Cadet {
	if x != nil {
		return x.Cadets
	}
	return nil
}

type CadetsTimeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ModuleId int32 `protobuf:"varint,1,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	// string from_date = 2;
	// string to_date = 3;
	FromDate *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=from_date,json=fromDate,proto3" json:"from_date,omitempty"`
	ToDate   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=to_date,json=toDate,proto3" json:"to_date,omitempty"`
}

func (x *CadetsTimeRequest) Reset() {
	*x = CadetsTimeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cadets_time_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CadetsTimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CadetsTimeRequest) ProtoMessage() {}

func (x *CadetsTimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cadets_time_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CadetsTimeRequest.ProtoReflect.Descriptor instead.
func (*CadetsTimeRequest) Descriptor() ([]byte, []int) {
	return file_cadets_time_proto_rawDescGZIP(), []int{3}
}

func (x *CadetsTimeRequest) GetModuleId() int32 {
	if x != nil {
		return x.ModuleId
	}
	return 0
}

func (x *CadetsTimeRequest) GetFromDate() *timestamppb.Timestamp {
	if x != nil {
		return x.FromDate
	}
	return nil
}

func (x *CadetsTimeRequest) GetToDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ToDate
	}
	return nil
}

var File_cadets_time_proto protoreflect.FileDescriptor

var file_cadets_time_proto_rawDesc = []byte{
	0x0a, 0x11, 0x63, 0x61, 0x64, 0x65, 0x74, 0x73, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x72, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x68, 0x0a, 0x08, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x4e, 0x75,
	0x6d, 0x12, 0x12, 0x0a, 0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x79, 0x65, 0x61, 0x72, 0x12, 0x32, 0x0a, 0x05, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x6d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x52, 0x05, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x68, 0x6f, 0x75,
	0x72, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x68, 0x6f, 0x75, 0x72, 0x73, 0x22,
	0x5e, 0x0a, 0x05, 0x43, 0x61, 0x64, 0x65, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x2f,
	0x0a, 0x05, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e,
	0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x4e, 0x75, 0x6d, 0x52, 0x05, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x22,
	0x5e, 0x0a, 0x12, 0x43, 0x61, 0x64, 0x65, 0x74, 0x73, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x2e, 0x0a, 0x06, 0x63, 0x61, 0x64, 0x65, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x72, 0x2e, 0x43, 0x61, 0x64, 0x65, 0x74, 0x52, 0x06, 0x63, 0x61, 0x64, 0x65, 0x74, 0x73, 0x22,
	0x9e, 0x01, 0x0a, 0x11, 0x43, 0x61, 0x64, 0x65, 0x74, 0x73, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65,
	0x49, 0x64, 0x12, 0x37, 0x0a, 0x09, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x65, 0x12, 0x33, 0x0a, 0x07, 0x74,
	0x6f, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x06, 0x74, 0x6f, 0x44, 0x61, 0x74, 0x65,
	0x2a, 0xb0, 0x01, 0x0a, 0x0b, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x0b, 0x0a, 0x07, 0x6a, 0x61, 0x6e, 0x75, 0x61, 0x72, 0x79, 0x10, 0x01, 0x12, 0x0c,
	0x0a, 0x08, 0x66, 0x65, 0x62, 0x72, 0x75, 0x61, 0x72, 0x79, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05,
	0x6d, 0x61, 0x72, 0x63, 0x68, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x61, 0x70, 0x72, 0x69, 0x6c,
	0x10, 0x04, 0x12, 0x07, 0x0a, 0x03, 0x6d, 0x61, 0x79, 0x10, 0x05, 0x12, 0x08, 0x0a, 0x04, 0x6a,
	0x75, 0x6e, 0x65, 0x10, 0x06, 0x12, 0x08, 0x0a, 0x04, 0x6a, 0x75, 0x6c, 0x79, 0x10, 0x07, 0x12,
	0x0a, 0x0a, 0x06, 0x61, 0x75, 0x67, 0x75, 0x73, 0x74, 0x10, 0x08, 0x12, 0x0d, 0x0a, 0x09, 0x73,
	0x65, 0x70, 0x74, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x10, 0x09, 0x12, 0x0b, 0x0a, 0x07, 0x6f, 0x63,
	0x74, 0x6f, 0x62, 0x65, 0x72, 0x10, 0x0a, 0x12, 0x0c, 0x0a, 0x08, 0x6e, 0x6f, 0x76, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x10, 0x0b, 0x12, 0x0c, 0x0a, 0x08, 0x64, 0x65, 0x63, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x10, 0x0c, 0x32, 0x74, 0x0a, 0x0e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x72, 0x12, 0x62, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x43, 0x61, 0x64, 0x65,
	0x74, 0x73, 0x54, 0x69, 0x6d, 0x65, 0x42, 0x79, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x49, 0x44,
	0x12, 0x22, 0x2e, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x72, 0x2e, 0x43, 0x61, 0x64, 0x65, 0x74, 0x73, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x6d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x43, 0x61, 0x64, 0x65, 0x74, 0x73, 0x54, 0x69, 0x6d,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x29, 0x5a, 0x27, 0x2f, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72,
	0x79, 0x2f, 0x70, 0x62, 0x2f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cadets_time_proto_rawDescOnce sync.Once
	file_cadets_time_proto_rawDescData = file_cadets_time_proto_rawDesc
)

func file_cadets_time_proto_rawDescGZIP() []byte {
	file_cadets_time_proto_rawDescOnce.Do(func() {
		file_cadets_time_proto_rawDescData = protoimpl.X.CompressGZIP(file_cadets_time_proto_rawDescData)
	})
	return file_cadets_time_proto_rawDescData
}

var file_cadets_time_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cadets_time_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_cadets_time_proto_goTypes = []interface{}{
	(MonthNumber)(0),              // 0: session_manager.MonthNumber
	(*MonthNum)(nil),              // 1: session_manager.MonthNum
	(*Cadet)(nil),                 // 2: session_manager.Cadet
	(*CadetsTimeResponse)(nil),    // 3: session_manager.CadetsTimeResponse
	(*CadetsTimeRequest)(nil),     // 4: session_manager.CadetsTimeRequest
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_cadets_time_proto_depIdxs = []int32{
	0, // 0: session_manager.MonthNum.month:type_name -> session_manager.MonthNumber
	1, // 1: session_manager.Cadet.month:type_name -> session_manager.MonthNum
	2, // 2: session_manager.CadetsTimeResponse.cadets:type_name -> session_manager.Cadet
	5, // 3: session_manager.CadetsTimeRequest.from_date:type_name -> google.protobuf.Timestamp
	5, // 4: session_manager.CadetsTimeRequest.to_date:type_name -> google.protobuf.Timestamp
	4, // 5: session_manager.SessionManager.GetCadetsTimeByModuleID:input_type -> session_manager.CadetsTimeRequest
	3, // 6: session_manager.SessionManager.GetCadetsTimeByModuleID:output_type -> session_manager.CadetsTimeResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_cadets_time_proto_init() }
func file_cadets_time_proto_init() {
	if File_cadets_time_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cadets_time_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MonthNum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cadets_time_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cadet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cadets_time_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CadetsTimeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cadets_time_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CadetsTimeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cadets_time_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cadets_time_proto_goTypes,
		DependencyIndexes: file_cadets_time_proto_depIdxs,
		EnumInfos:         file_cadets_time_proto_enumTypes,
		MessageInfos:      file_cadets_time_proto_msgTypes,
	}.Build()
	File_cadets_time_proto = out.File
	file_cadets_time_proto_rawDesc = nil
	file_cadets_time_proto_goTypes = nil
	file_cadets_time_proto_depIdxs = nil
}
